/*************** <auto-copyright.rb BEGIN do not edit this line> **************
 *
 * Copyright 2012-2012 by Ames Laboratory
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Library General Public
 * License version 2.1 as published by the Free Software Foundation.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 *
 * You should have received a copy of the GNU Library General Public
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
 * Boston, MA 02111-1307, USA.
 *
 *************** <auto-copyright.rb END do not edit this line> ***************/
#pragma once

/// @file OdpXmlFiles.h
/// @namespace storyteller
/// This header contains boilerplate xml data that goes in various files
/// required of a valid .odp. Some of these strings contain ##KEYWORD## tags
/// that are searched for and replaced when we write the data out into the
/// respective files.

// TODO: The default data from OdpXmlFiles.h should only be
// used as a fallback when a master presentation is not given. It would be
// preferable in many circumstances to uncompress a master so that we don't
// have to write out the "UnchangedFiles" at all. Then we'd do some light
// parsing followed by S&R on content.xml, meta.xml, and manifest.xml. This
// would allow end users to supply custom masters with their own
// styles, default titles, footers, image size, etc. They would need to
// supply a valid .odp -- not a .odt template -- which contains, among
// any other slides with other content, a single slide containing an image
// of the desired aspect ratio which has had its frame named
// "STORYTELLER_IMAGE_HOLDER" by right-clicking on the image and selecting the
// "Name..." menu option. There should be only *one* slide with a
// "STORYTELLER_IMAGE_HOLDER". This slide will get copied over and over by storyteller,
// with the image residing in STORYTELLER_IMAGE_HOLDER being replaced each time
// by the images given to storyteller. The dummy image supplied in the master will
// be deleted from the Pictures subdir and removed from the manifest.

namespace storyteller
{

const char* mimetype = {"application/vnd.oasis.opendocument.presentation"};

const char* settings = {
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    "    <office:document-settings "
    "xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" "
    "xmlns:xlink=\"http://www.w3.org/1999/xlink\" "
    "xmlns:presentation=\"urn:oasis:names:tc:opendocument:xmlns:presentatio"
    "n:1.0\" "
    "xmlns:config=\"urn:oasis:names:tc:opendocument:xmlns:config:1.0\" "
    "xmlns:ooo=\"http://openoffice.org/2004/office\" "
    "xmlns:smil=\"urn:oasis:names:tc:opendocument:xmlns:smil-compatible:1.0"
    "\" xmlns:anim=\"urn:oasis:names:tc:opendocument:xmlns:animation:1.0\" "
    "xmlns:officeooo=\"http://openoffice.org/2009/office\" "
    "xmlns:drawooo=\"http://openoffice.org/2010/draw\" "
    "office:version=\"1.2\"><office:settings><config:config-item-set "
    "config:name=\"ooo:view-settings\"><config:config-item "
    "config:name=\"VisibleAreaTop\" "
    "config:type=\"int\">-309</config:config-item><config:config-item "
    "config:name=\"VisibleAreaLeft\" "
    "config:type=\"int\">-5336</config:config-item><config:config-item "
    "config:name=\"VisibleAreaWidth\" "
    "config:type=\"int\">39247</config:config-item><config:config-item "
    "config:name=\"VisibleAreaHeight\" "
    "config:type=\"int\">21916</config:config-item><config:config-item-map-"
    "indexed "
    "config:name=\"Views\"><config:config-item-map-entry><config:config-ite"
    "m config:name=\"ViewId\" "
    "config:type=\"string\">view1</config:config-item><config:config-item "
    "config:name=\"GridIsVisible\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"GridIsFront\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsstorytellerToGrid\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"IsstorytellerToPageMargins\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"IsstorytellerTostorytellerLines\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"IsstorytellerToObjectFrame\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"IsstorytellerToObjectPoints\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPlusHandlesAlwaysVisible\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsFrameDragSingles\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"EliminatePolyPointLimitAngle\" "
    "config:type=\"int\">1500</config:config-item><config:config-item "
    "config:name=\"IsEliminatePolyPoints\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"VisibleLayers\" "
    "config:type=\"base64Binary\">/////////////////////////////////////////"
    "/8=</config:config-item><config:config-item "
    "config:name=\"PrintableLayers\" "
    "config:type=\"base64Binary\">/////////////////////////////////////////"
    "/8=</config:config-item><config:config-item "
    "config:name=\"LockedLayers\" "
    "config:type=\"base64Binary\"/><config:config-item "
    "config:name=\"NoAttribs\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"NoColors\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"RulerIsVisible\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"PageKind\" "
    "config:type=\"short\">0</config:config-item><config:config-item "
    "config:name=\"SelectedPage\" "
    "config:type=\"short\">0</config:config-item><config:config-item "
    "config:name=\"IsLayerMode\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsDoubleClickTextEdit\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"IsClickChangeRotation\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"SlidesPerRow\" "
    "config:type=\"short\">4</config:config-item><config:config-item "
    "config:name=\"EditModeStandard\" "
    "config:type=\"int\">0</config:config-item><config:config-item "
    "config:name=\"EditModeNotes\" "
    "config:type=\"int\">0</config:config-item><config:config-item "
    "config:name=\"EditModeHandout\" "
    "config:type=\"int\">1</config:config-item><config:config-item "
    "config:name=\"VisibleAreaTop\" "
    "config:type=\"int\">-309</config:config-item><config:config-item "
    "config:name=\"VisibleAreaLeft\" "
    "config:type=\"int\">-5336</config:config-item><config:config-item "
    "config:name=\"VisibleAreaWidth\" "
    "config:type=\"int\">39248</config:config-item><config:config-item "
    "config:name=\"VisibleAreaHeight\" "
    "config:type=\"int\">21917</config:config-item><config:config-item "
    "config:name=\"GridCoarseWidth\" "
    "config:type=\"int\">2540</config:config-item><config:config-item "
    "config:name=\"GridCoarseHeight\" "
    "config:type=\"int\">2540</config:config-item><config:config-item "
    "config:name=\"GridFineWidth\" "
    "config:type=\"int\">254</config:config-item><config:config-item "
    "config:name=\"GridFineHeight\" "
    "config:type=\"int\">254</config:config-item><config:config-item "
    "config:name=\"GridstorytellerWidthXNumerator\" "
    "config:type=\"int\">254</config:config-item><config:config-item "
    "config:name=\"GridstorytellerWidthXDenominator\" "
    "config:type=\"int\">1</config:config-item><config:config-item "
    "config:name=\"GridstorytellerWidthYNumerator\" "
    "config:type=\"int\">254</config:config-item><config:config-item "
    "config:name=\"GridstorytellerWidthYDenominator\" "
    "config:type=\"int\">1</config:config-item><config:config-item "
    "config:name=\"IsAnglestorytellerEnabled\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"storytellerAngle\" "
    "config:type=\"int\">1500</config:config-item><config:config-item "
    "config:name=\"ZoomOnPage\" "
    "config:type=\"boolean\">true</config:config-item></config:config-item-"
    "map-entry></config:config-item-map-indexed></config:config-item-set><c"
    "onfig:config-item-set "
    "config:name=\"ooo:configuration-settings\"><config:config-item "
    "config:name=\"ApplyUserData\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"BitmapTableURL\" "
    "config:type=\"string\">$(user)/config/standard.sob</config:config-item"
    "><config:config-item config:name=\"CharacterCompressionType\" "
    "config:type=\"short\">0</config:config-item><config:config-item "
    "config:name=\"ColorTableURL\" "
    "config:type=\"string\">$(user)/config/standard.soc</config:config-item"
    "><config:config-item config:name=\"DashTableURL\" "
    "config:type=\"string\">$(user)/config/standard.sod</config:config-item"
    "><config:config-item config:name=\"DefaultTabStop\" "
    "config:type=\"int\">1270</config:config-item><config:config-item-map-i"
    "ndexed "
    "config:name=\"ForbiddenCharacters\"><config:config-item-map-entry><con"
    "fig:config-item config:name=\"Language\" "
    "config:type=\"string\">en</config:config-item><config:config-item "
    "config:name=\"Country\" "
    "config:type=\"string\">US</config:config-item><config:config-item "
    "config:name=\"Variant\" config:type=\"string\"/><config:config-item "
    "config:name=\"BeginLine\" config:type=\"string\"/><config:config-item "
    "config:name=\"EndLine\" "
    "config:type=\"string\"/></config:config-item-map-entry></config:config"
    "-item-map-indexed><config:config-item "
    "config:name=\"GradientTableURL\" "
    "config:type=\"string\">$(user)/config/standard.sog</config:config-item"
    "><config:config-item config:name=\"HandoutsHorizontal\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"HatchTableURL\" "
    "config:type=\"string\">$(user)/config/standard.soh</config:config-item"
    "><config:config-item config:name=\"IsKernAsianPunctuation\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPrintBooklet\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPrintBookletBack\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"IsPrintBookletFront\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"IsPrintDate\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPrintDrawing\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"IsPrintFitPage\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPrintHandout\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPrintHiddenPages\" "
    "config:type=\"boolean\">true</config:config-item><config:config-item "
    "config:name=\"IsPrintNotes\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPrintOutline\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPrintPageName\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPrintTilePage\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"IsPrintTime\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"LineEndTableURL\" "
    "config:type=\"string\">$(user)/config/standard.soe</config:config-item"
    "><config:config-item config:name=\"LoadReadonly\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"PageNumberFormat\" "
    "config:type=\"int\">4</config:config-item><config:config-item "
    "config:name=\"ParagraphSummation\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"PrintQuality\" "
    "config:type=\"int\">0</config:config-item><config:config-item "
    "config:name=\"PrinterIndependentLayout\" "
    "config:type=\"string\">low-resolution</config:config-item><config:conf"
    "ig-item config:name=\"PrinterName\" "
    "config:type=\"string\">PDF</config:config-item><config:config-item "
    "config:name=\"PrinterSetup\" "
    "config:type=\"base64Binary\">fAH+/1BERgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQ1VQU"
    "zpQREYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWAAMAngAAAAAAAAAIAFZUAAAkbQAASm9"
    "iRGF0YSAxCnByaW50ZXI9UERGCm9yaWVudGF0aW9uPVBvcnRyYWl0CmNvcGllcz0xCm1hc"
    "mdpbmRhanVzdG1lbnQ9MCwwLDAsMApjb2xvcmRlcHRoPTI0CnBzbGV2ZWw9MApwZGZkZXZ"
    "pY2U9MQpjb2xvcmRldmljZT0wClBQRENvbnRleERhdGEKUGFnZVNpemU6TGV0dGVyAAASA"
    "ENPTVBBVF9EVVBMRVhfTU9ERQ4ARFVQTEVYX1VOS05PV04=</config:config-item><c"
    "onfig:config-item config:name=\"SaveVersionOnClose\" "
    "config:type=\"boolean\">false</config:config-item><config:config-item "
    "config:name=\"SlidesPerHandout\" "
    "config:type=\"short\">6</config:config-item><config:config-item "
    "config:name=\"UpdateFromTemplate\" "
    "config:type=\"boolean\">true</config:config-item></config:config-item-"
    "set></office:settings></office:document-settings>\n"
};

const char* styles = {
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<office:document-styles "
        "xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" "
        "xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" "
        "xmlns:text=\"urn:oasis:names:tc:opendocument:xmlns:text:1.0\" "
        "xmlns:table=\"urn:oasis:names:tc:opendocument:xmlns:table:1.0\" "
        "xmlns:draw=\"urn:oasis:names:tc:opendocument:xmlns:drawing:1.0\" "
        "xmlns:fo=\"urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
        "\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" "
        "xmlns:dc=\"http://purl.org/dc/elements/1.1/\" "
        "xmlns:meta=\"urn:oasis:names:tc:opendocument:xmlns:meta:1.0\" "
        "xmlns:number=\"urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0\" "
        "xmlns:presentation=\"urn:oasis:names:tc:opendocument:xmlns:presentatio"
        "n:1.0\" "
        "xmlns:svg=\"urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0\""
        " xmlns:chart=\"urn:oasis:names:tc:opendocument:xmlns:chart:1.0\" "
        "xmlns:dr3d=\"urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0\" "
        "xmlns:math=\"http://www.w3.org/1998/Math/MathML\" "
        "xmlns:form=\"urn:oasis:names:tc:opendocument:xmlns:form:1.0\" "
        "xmlns:script=\"urn:oasis:names:tc:opendocument:xmlns:script:1.0\" "
        "xmlns:ooo=\"http://openoffice.org/2004/office\" "
        "xmlns:ooow=\"http://openoffice.org/2004/writer\" "
        "xmlns:oooc=\"http://openoffice.org/2004/calc\" "
        "xmlns:dom=\"http://www.w3.org/2001/xml-events\" "
        "xmlns:smil=\"urn:oasis:names:tc:opendocument:xmlns:smil-compatible:1.0"
        "\" xmlns:anim=\"urn:oasis:names:tc:opendocument:xmlns:animation:1.0\" "
        "xmlns:rpt=\"http://openoffice.org/2005/report\" "
        "xmlns:of=\"urn:oasis:names:tc:opendocument:xmlns:of:1.2\" "
        "xmlns:xhtml=\"http://www.w3.org/1999/xhtml\" "
        "xmlns:grddl=\"http://www.w3.org/2003/g/data-view#\" "
        "xmlns:officeooo=\"http://openoffice.org/2009/office\" "
        "xmlns:tableooo=\"http://openoffice.org/2009/table\" "
        "xmlns:drawooo=\"http://openoffice.org/2010/draw\" "
        "xmlns:css3t=\"http://www.w3.org/TR/css3-text/\" "
        "office:version=\"1.2\"><office:styles><draw:marker "
        "draw:name=\"Arrow\" svg:viewBox=\"0 0 20 30\" svg:d=\"m10 0-10 "
        "30h20z\"/><style:default-style "
        "style:family=\"graphic\"><style:graphic-properties "
        "svg:stroke-color=\"#808080\" draw:fill-color=\"#cfe7f5\" "
        "fo:wrap-option=\"no-wrap\"/><style:paragraph-properties "
        "style:text-autospace=\"ideograph-alpha\" "
        "style:punctuation-wrap=\"simple\" style:line-break=\"strict\" "
        "style:writing-mode=\"lr-tb\" "
        "style:font-independent-line-spacing=\"false\"><style:tab-stops/></styl"
        "e:paragraph-properties><style:text-properties "
        "style:use-window-font-color=\"true\" fo:font-family=\"&apos;Times New "
        "Roman&apos;\" style:font-family-generic=\"roman\" "
        "style:font-pitch=\"variable\" fo:font-size=\"24pt\" "
        "fo:language=\"en\" fo:country=\"US\" "
        "style:font-family-asian=\"&apos;DejaVu Sans&apos;\" "
        "style:font-family-generic-asian=\"system\" "
        "style:font-pitch-asian=\"variable\" style:font-size-asian=\"24pt\" "
        "style:language-asian=\"zh\" style:country-asian=\"CN\" "
        "style:font-family-complex=\"&apos;DejaVu Sans&apos;\" "
        "style:font-family-generic-complex=\"system\" "
        "style:font-pitch-complex=\"variable\" "
        "style:font-size-complex=\"24pt\" style:language-complex=\"hi\" "
        "style:country-complex=\"IN\"/></style:default-style><style:style "
        "style:name=\"standard\" "
        "style:family=\"graphic\"><style:graphic-properties "
        "draw:stroke=\"solid\" svg:stroke-width=\"0cm\" "
        "svg:stroke-color=\"#808080\" draw:marker-start-width=\"0.2cm\" "
        "draw:marker-start-center=\"false\" draw:marker-end-width=\"0.2cm\" "
        "draw:marker-end-center=\"false\" draw:fill=\"solid\" "
        "draw:fill-color=\"#cfe7f5\" "
        "draw:textarea-horizontal-align=\"justify\" fo:padding-top=\"0.125cm\" "
        "fo:padding-bottom=\"0.125cm\" fo:padding-left=\"0.25cm\" "
        "fo:padding-right=\"0.25cm\" draw:shadow=\"hidden\" "
        "draw:shadow-offset-x=\"0.2cm\" draw:shadow-offset-y=\"0.2cm\" "
        "draw:shadow-color=\"#808080\"><text:list-style "
        "style:name=\"standard\"><text:list-level-style-bullet "
        "text:level=\"1\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"2\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"0.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"3\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"4\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"5\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"2.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"6\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"7\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"8\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"9\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"10\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"5.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet></text:list-style"
        "></style:graphic-properties><style:paragraph-properties "
        "fo:margin-left=\"0cm\" fo:margin-right=\"0cm\" fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0cm\" fo:line-height=\"100%\" "
        "fo:text-indent=\"0cm\"/><style:text-properties "
        "style:use-window-font-color=\"true\" style:text-outline=\"false\" "
        "style:text-line-through-style=\"none\" fo:font-family=\"Arial\" "
        "style:font-family-generic=\"roman\" style:font-pitch=\"variable\" "
        "fo:font-size=\"18pt\" fo:font-style=\"normal\" "
        "fo:text-shadow=\"none\" style:text-underline-style=\"none\" "
        "fo:font-weight=\"normal\" style:letter-kerning=\"true\" "
        "style:font-family-asian=\"&apos;WenQuanYi Micro Hei&apos;\" "
        "style:font-family-generic-asian=\"system\" "
        "style:font-pitch-asian=\"variable\" style:font-size-asian=\"18pt\" "
        "style:font-style-asian=\"normal\" style:font-weight-asian=\"normal\" "
        "style:font-family-complex=\"&apos;Lohit Hindi&apos;\" "
        "style:font-family-generic-complex=\"system\" "
        "style:font-pitch-complex=\"variable\" "
        "style:font-size-complex=\"18pt\" style:font-style-complex=\"normal\" "
        "style:font-weight-complex=\"normal\" style:text-emphasize=\"none\" "
        "style:font-relief=\"none\" style:text-overline-style=\"none\" "
        "style:text-overline-color=\"font-color\"/></style:style><style:style "
        "style:name=\"objectwitharrow\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"solid\" svg:stroke-width=\"0.15cm\" "
        "svg:stroke-color=\"#000000\" draw:marker-start=\"Arrow\" "
        "draw:marker-start-width=\"0.7cm\" draw:marker-start-center=\"true\" "
        "draw:marker-end-width=\"0.3cm\"/></style:style><style:style "
        "style:name=\"objectwithshadow\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:shadow=\"visible\" draw:shadow-offset-x=\"0.2cm\" "
        "draw:shadow-offset-y=\"0.2cm\" "
        "draw:shadow-color=\"#808080\"/></style:style><style:style "
        "style:name=\"objectwithoutfill\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "svg:stroke-color=\"#000000\" "
        "draw:fill=\"none\"/></style:style><style:style style:name=\"text\" "
        "style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/></style:style><style:style "
        "style:name=\"textbody\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/><style:text-properties "
        "fo:font-size=\"16pt\"/></style:style><style:style "
        "style:name=\"textbodyjustfied\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/><style:paragraph-properties "
        "fo:text-align=\"justify\"/></style:style><style:style "
        "style:name=\"textbodyindent\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/><style:paragraph-properties "
        "fo:margin-left=\"0cm\" fo:margin-right=\"0cm\" "
        "fo:text-indent=\"0.6cm\"/></style:style><style:style "
        "style:name=\"title\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/><style:text-properties "
        "fo:font-size=\"44pt\"/></style:style><style:style "
        "style:name=\"title1\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"solid\" draw:fill-color=\"#008080\" "
        "draw:shadow=\"visible\" draw:shadow-offset-x=\"0.2cm\" "
        "draw:shadow-offset-y=\"0.2cm\" "
        "draw:shadow-color=\"#808080\"/><style:paragraph-properties "
        "fo:text-align=\"center\"/><style:text-properties "
        "fo:font-size=\"24pt\"/></style:style><style:style "
        "style:name=\"title2\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "svg:stroke-width=\"0.05cm\" draw:fill-color=\"#ffcc99\" "
        "draw:shadow=\"visible\" draw:shadow-offset-x=\"0.2cm\" "
        "draw:shadow-offset-y=\"0.2cm\" "
        "draw:shadow-color=\"#808080\"/><style:paragraph-properties "
        "fo:margin-left=\"0cm\" fo:margin-right=\"0.2cm\" "
        "fo:margin-top=\"0.1cm\" fo:margin-bottom=\"0.1cm\" "
        "fo:text-align=\"center\" "
        "fo:text-indent=\"0cm\"/><style:text-properties "
        "fo:font-size=\"36pt\"/></style:style><style:style "
        "style:name=\"headline\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/><style:paragraph-properties "
        "fo:margin-top=\"0.42cm\" "
        "fo:margin-bottom=\"0.21cm\"/><style:text-properties "
        "fo:font-size=\"24pt\"/></style:style><style:style "
        "style:name=\"headline1\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/><style:paragraph-properties "
        "fo:margin-top=\"0.42cm\" "
        "fo:margin-bottom=\"0.21cm\"/><style:text-properties "
        "fo:font-size=\"18pt\" "
        "fo:font-weight=\"bold\"/></style:style><style:style "
        "style:name=\"headline2\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/><style:paragraph-properties "
        "fo:margin-top=\"0.42cm\" "
        "fo:margin-bottom=\"0.21cm\"/><style:text-properties "
        "fo:font-size=\"14pt\" fo:font-style=\"italic\" "
        "fo:font-weight=\"bold\"/></style:style><style:style "
        "style:name=\"measure\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"solid\" svg:stroke-color=\"#000000\" "
        "draw:marker-start=\"Arrow\" draw:marker-start-width=\"0.2cm\" "
        "draw:marker-end=\"Arrow\" draw:marker-end-width=\"0.2cm\" "
        "draw:fill=\"none\" draw:show-unit=\"true\"/><style:text-properties "
        "fo:font-size=\"12pt\"/></style:style><style:style "
        "style:name=\"Default-background\" "
        "style:family=\"presentation\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/><style:text-properties "
        "style:letter-kerning=\"true\"/></style:style><style:style "
        "style:name=\"Default-backgroundobjects\" "
        "style:family=\"presentation\"><style:graphic-properties "
        "draw:textarea-horizontal-align=\"justify\" draw:shadow=\"hidden\" "
        "draw:shadow-offset-x=\"0.2cm\" draw:shadow-offset-y=\"0.2cm\" "
        "draw:shadow-color=\"#808080\"/><style:text-properties "
        "style:letter-kerning=\"true\"/></style:style><style:style "
        "style:name=\"Default-notes\" "
        "style:family=\"presentation\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\"/><style:paragraph-properties "
        "fo:margin-left=\"0.6cm\" fo:margin-right=\"0cm\" "
        "fo:text-indent=\"-0.6cm\"/><style:text-properties "
        "style:use-window-font-color=\"true\" style:text-outline=\"false\" "
        "style:text-line-through-style=\"none\" fo:font-family=\"Arial\" "
        "style:font-family-generic=\"roman\" style:font-pitch=\"variable\" "
        "fo:font-size=\"20pt\" fo:font-style=\"normal\" "
        "fo:text-shadow=\"none\" style:text-underline-style=\"none\" "
        "fo:font-weight=\"normal\" style:letter-kerning=\"true\" "
        "style:font-family-asian=\"&apos;WenQuanYi Micro Hei&apos;\" "
        "style:font-family-generic-asian=\"system\" "
        "style:font-pitch-asian=\"variable\" style:font-size-asian=\"20pt\" "
        "style:font-style-asian=\"normal\" style:font-weight-asian=\"normal\" "
        "style:font-family-complex=\"&apos;Lohit Hindi&apos;\" "
        "style:font-family-generic-complex=\"system\" "
        "style:font-pitch-complex=\"variable\" "
        "style:font-size-complex=\"20pt\" style:font-style-complex=\"normal\" "
        "style:font-weight-complex=\"normal\" style:text-emphasize=\"none\" "
        "style:font-relief=\"none\" style:text-overline-style=\"none\" "
        "style:text-overline-color=\"font-color\"/></style:style><style:style "
        "style:name=\"Default-outline1\" "
        "style:family=\"presentation\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\" "
        "draw:auto-grow-height=\"false\" "
        "draw:fit-to-size=\"shrink-to-fit\"><text:list-style "
        "style:name=\"Default-outline1\"><text:list-level-style-bullet "
        "text:level=\"1\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"0.3cm\" "
        "text:min-label-width=\"0.9cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"2\" "
        "text:bullet-char=\"–\"><style:list-level-properties "
        "text:space-before=\"1.5cm\" "
        "text:min-label-width=\"0.9cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"75%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"3\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"2.8cm\" "
        "text:min-label-width=\"0.8cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"4\" "
        "text:bullet-char=\"–\"><style:list-level-properties "
        "text:space-before=\"4.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"75%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"5\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"5.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"6\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"6.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"7\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"7.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"8\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"9cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"9\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"10.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"10\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"11.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet></text:list-style"
        "></style:graphic-properties><style:paragraph-properties "
        "fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0.5cm\"/><style:text-properties "
        "style:use-window-font-color=\"true\" style:text-outline=\"false\" "
        "style:text-line-through-style=\"none\" fo:font-family=\"Arial\" "
        "style:font-family-generic=\"roman\" style:font-pitch=\"variable\" "
        "fo:font-size=\"32pt\" fo:font-style=\"normal\" "
        "fo:text-shadow=\"none\" style:text-underline-style=\"none\" "
        "fo:font-weight=\"normal\" style:letter-kerning=\"true\" "
        "style:font-family-asian=\"&apos;WenQuanYi Micro Hei&apos;\" "
        "style:font-family-generic-asian=\"system\" "
        "style:font-pitch-asian=\"variable\" style:font-size-asian=\"32pt\" "
        "style:font-style-asian=\"normal\" style:font-weight-asian=\"normal\" "
        "style:font-family-complex=\"&apos;Lohit Hindi&apos;\" "
        "style:font-family-generic-complex=\"system\" "
        "style:font-pitch-complex=\"variable\" "
        "style:font-size-complex=\"32pt\" style:font-style-complex=\"normal\" "
        "style:font-weight-complex=\"normal\" style:text-emphasize=\"none\" "
        "style:font-relief=\"none\" style:text-overline-style=\"none\" "
        "style:text-overline-color=\"font-color\"/></style:style><style:style "
        "style:name=\"Default-outline2\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-outline1\"><style:paragraph-properti"
        "es fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0.4cm\"/><style:text-properties "
        "fo:font-size=\"28pt\" style:font-size-asian=\"28pt\" "
        "style:font-size-complex=\"28pt\"/></style:style><style:style "
        "style:name=\"Default-outline3\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-outline2\"><style:paragraph-properti"
        "es fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0.3cm\"/><style:text-properties "
        "fo:font-size=\"24pt\" style:font-size-asian=\"24pt\" "
        "style:font-size-complex=\"24pt\"/></style:style><style:style "
        "style:name=\"Default-outline4\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-outline3\"><style:paragraph-properti"
        "es fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0.2cm\"/><style:text-properties "
        "fo:font-size=\"20pt\" style:font-size-asian=\"20pt\" "
        "style:font-size-complex=\"20pt\"/></style:style><style:style "
        "style:name=\"Default-outline5\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-outline4\"><style:paragraph-properti"
        "es fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0.1cm\"/><style:text-properties "
        "fo:font-size=\"20pt\" style:font-size-asian=\"20pt\" "
        "style:font-size-complex=\"20pt\"/></style:style><style:style "
        "style:name=\"Default-outline6\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-outline5\"><style:paragraph-properti"
        "es fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0.1cm\"/><style:text-properties "
        "fo:font-size=\"20pt\" style:font-size-asian=\"20pt\" "
        "style:font-size-complex=\"20pt\"/></style:style><style:style "
        "style:name=\"Default-outline7\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-outline6\"><style:paragraph-properti"
        "es fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0.1cm\"/><style:text-properties "
        "fo:font-size=\"20pt\" style:font-size-asian=\"20pt\" "
        "style:font-size-complex=\"20pt\"/></style:style><style:style "
        "style:name=\"Default-outline8\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-outline7\"><style:paragraph-properti"
        "es fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0.1cm\"/><style:text-properties "
        "fo:font-size=\"20pt\" style:font-size-asian=\"20pt\" "
        "style:font-size-complex=\"20pt\"/></style:style><style:style "
        "style:name=\"Default-outline9\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-outline8\"><style:paragraph-properti"
        "es fo:margin-top=\"0cm\" "
        "fo:margin-bottom=\"0.1cm\"/><style:text-properties "
        "fo:font-size=\"20pt\" style:font-size-asian=\"20pt\" "
        "style:font-size-complex=\"20pt\"/></style:style><style:style "
        "style:name=\"Default-subtitle\" "
        "style:family=\"presentation\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\" "
        "draw:textarea-vertical-align=\"middle\"><text:list-style "
        "style:name=\"Default-subtitle\"><text:list-level-style-bullet "
        "text:level=\"1\" "
        "text:bullet-char=\"●\"><style:list-level-properties/><style:text-pro"
        "perties fo:font-family=\"StarSymbol\" "
        "style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"2\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"0.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"3\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"4\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"5\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"2.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"6\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"7\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"8\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"9\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"10\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"5.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet></text:list-style"
        "></style:graphic-properties><style:paragraph-properties "
        "fo:margin-left=\"0cm\" fo:margin-right=\"0cm\" "
        "fo:text-align=\"center\" "
        "fo:text-indent=\"0cm\"/><style:text-properties "
        "style:use-window-font-color=\"true\" style:text-outline=\"false\" "
        "style:text-line-through-style=\"none\" fo:font-family=\"Arial\" "
        "style:font-family-generic=\"roman\" style:font-pitch=\"variable\" "
        "fo:font-size=\"32pt\" fo:font-style=\"normal\" "
        "fo:text-shadow=\"none\" style:text-underline-style=\"none\" "
        "fo:font-weight=\"normal\" style:letter-kerning=\"true\" "
        "style:font-family-asian=\"&apos;WenQuanYi Micro Hei&apos;\" "
        "style:font-family-generic-asian=\"system\" "
        "style:font-pitch-asian=\"variable\" style:font-size-asian=\"32pt\" "
        "style:font-style-asian=\"normal\" style:font-weight-asian=\"normal\" "
        "style:font-family-complex=\"&apos;Lohit Hindi&apos;\" "
        "style:font-family-generic-complex=\"system\" "
        "style:font-pitch-complex=\"variable\" "
        "style:font-size-complex=\"32pt\" style:font-style-complex=\"normal\" "
        "style:font-weight-complex=\"normal\" style:text-emphasize=\"none\" "
        "style:font-relief=\"none\" style:text-overline-style=\"none\" "
        "style:text-overline-color=\"font-color\"/></style:style><style:style "
        "style:name=\"Default-title\" "
        "style:family=\"presentation\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\" "
        "draw:textarea-vertical-align=\"middle\"><text:list-style "
        "style:name=\"Default-title\"><text:list-level-style-bullet "
        "text:level=\"1\" "
        "text:bullet-char=\"●\"><style:list-level-properties/><style:text-pro"
        "perties fo:font-family=\"StarSymbol\" "
        "style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"2\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"0.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"3\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"4\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"5\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"2.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"6\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"7\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"8\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"9\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"10\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"5.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet></text:list-style"
        "></style:graphic-properties><style:paragraph-properties "
        "fo:text-align=\"center\"/><style:text-properties "
        "style:use-window-font-color=\"true\" style:text-outline=\"false\" "
        "style:text-line-through-style=\"none\" fo:font-family=\"Arial\" "
        "style:font-family-generic=\"roman\" style:font-pitch=\"variable\" "
        "fo:font-size=\"44pt\" fo:font-style=\"normal\" "
        "fo:text-shadow=\"none\" style:text-underline-style=\"none\" "
        "fo:font-weight=\"normal\" style:letter-kerning=\"true\" "
        "style:font-family-asian=\"&apos;WenQuanYi Micro Hei&apos;\" "
        "style:font-family-generic-asian=\"system\" "
        "style:font-pitch-asian=\"variable\" style:font-size-asian=\"44pt\" "
        "style:font-style-asian=\"normal\" style:font-weight-asian=\"normal\" "
        "style:font-family-complex=\"&apos;Lohit Hindi&apos;\" "
        "style:font-family-generic-complex=\"system\" "
        "style:font-pitch-complex=\"variable\" "
        "style:font-size-complex=\"44pt\" style:font-style-complex=\"normal\" "
        "style:font-weight-complex=\"normal\" style:text-emphasize=\"none\" "
        "style:font-relief=\"none\" style:text-overline-style=\"none\" "
        "style:text-overline-color=\"font-color\"/></style:style><style:present"
        "ation-page-layout style:name=\"AL0T26\"><presentation:placeholder "
        "presentation:object=\"handout\" svg:x=\"2.058cm\" svg:y=\"1.743cm\" "
        "svg:width=\"10.556cm\" "
        "svg:height=\"-0.233cm\"/><presentation:placeholder "
        "presentation:object=\"handout\" svg:x=\"15.414cm\" svg:y=\"1.743cm\" "
        "svg:width=\"10.556cm\" "
        "svg:height=\"-0.233cm\"/><presentation:placeholder "
        "presentation:object=\"handout\" svg:x=\"2.058cm\" svg:y=\"3.612cm\" "
        "svg:width=\"10.556cm\" "
        "svg:height=\"-0.233cm\"/><presentation:placeholder "
        "presentation:object=\"handout\" svg:x=\"15.414cm\" svg:y=\"3.612cm\" "
        "svg:width=\"10.556cm\" "
        "svg:height=\"-0.233cm\"/><presentation:placeholder "
        "presentation:object=\"handout\" svg:x=\"2.058cm\" svg:y=\"5.481cm\" "
        "svg:width=\"10.556cm\" "
        "svg:height=\"-0.233cm\"/><presentation:placeholder "
        "presentation:object=\"handout\" svg:x=\"15.414cm\" svg:y=\"5.481cm\" "
        "svg:width=\"10.556cm\" "
        "svg:height=\"-0.233cm\"/></style:presentation-page-layout><style:prese"
        "ntation-page-layout style:name=\"AL1T0\"><presentation:placeholder "
        "presentation:object=\"title\" svg:x=\"2.058cm\" svg:y=\"1.743cm\" "
        "svg:width=\"23.912cm\" "
        "svg:height=\"3.507cm\"/><presentation:placeholder "
        "presentation:object=\"subtitle\" svg:x=\"2.058cm\" svg:y=\"5.838cm\" "
        "svg:width=\"23.912cm\" "
        "svg:height=\"13.23cm\"/></style:presentation-page-layout></office:styl"
        "es><office:automatic-styles><style:page-layout "
        "style:name=\"PM0\"><style:page-layout-properties "
        "fo:margin-top=\"0cm\" fo:margin-bottom=\"0cm\" fo:margin-left=\"0cm\" "
        "fo:margin-right=\"0cm\" fo:page-width=\"21.59cm\" "
        "fo:page-height=\"27.94cm\" "
        "style:print-orientation=\"portrait\"/></style:page-layout><style:page-"
        "layout style:name=\"PM1\"><style:page-layout-properties "
        "fo:margin-top=\"0cm\" fo:margin-bottom=\"0cm\" fo:margin-left=\"0cm\" "
        "fo:margin-right=\"0cm\" fo:page-width=\"28cm\" "
        "fo:page-height=\"21cm\" "
        "style:print-orientation=\"landscape\"/></style:page-layout><style:styl"
        "e style:name=\"Mdp1\" "
        "style:family=\"drawing-page\"><style:drawing-page-properties "
        "draw:background-size=\"border\" "
        "draw:fill=\"none\"/></style:style><style:style style:name=\"Mdp2\" "
        "style:family=\"drawing-page\"><style:drawing-page-properties "
        "presentation:display-header=\"true\" "
        "presentation:display-footer=\"true\" "
        "presentation:display-page-number=\"false\" "
        "presentation:display-date-time=\"true\"/></style:style><style:style "
        "style:name=\"Mgr1\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\" draw:fill-color=\"#ffffff\" "
        "draw:auto-grow-height=\"false\" "
        "fo:min-height=\"1.397cm\"/></style:style><style:style "
        "style:name=\"Mgr2\" style:family=\"graphic\" "
        "style:parent-style-name=\"standard\"><style:graphic-properties "
        "draw:stroke=\"none\" draw:fill=\"none\" draw:fill-color=\"#ffffff\" "
        "draw:textarea-vertical-align=\"bottom\" "
        "draw:auto-grow-height=\"false\" "
        "fo:min-height=\"1.397cm\"/></style:style><style:style "
        "style:name=\"Mpr1\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-backgroundobjects\"><style:graphic-p"
        "roperties draw:stroke=\"none\" draw:fill=\"none\" "
        "draw:fill-color=\"#ffffff\" draw:auto-grow-height=\"false\" "
        "fo:min-height=\"1.449cm\"/></style:style><style:style "
        "style:name=\"Mpr2\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-backgroundobjects\"><style:graphic-p"
        "roperties draw:stroke=\"none\" draw:fill=\"none\" "
        "draw:fill-color=\"#ffffff\" draw:auto-grow-height=\"false\" "
        "fo:min-height=\"1.397cm\"/></style:style><style:style "
        "style:name=\"Mpr3\" style:family=\"presentation\" "
        "style:parent-style-name=\"Default-backgroundobjects\"><style:graphic-p"
        "roperties draw:stroke=\"none\" draw:fill=\"none\" "
        "draw:fill-color=\"#ffffff\" draw:textarea-vertical-align=\"bottom\" "
        "draw:auto-grow-height=\"false\" "
        "fo:min-height=\"1.397cm\"/></style:style><style:style "
        "style:name=\"MP1\" style:family=\"paragraph\"><style:text-properties "
        "fo:font-size=\"14pt\" style:font-size-asian=\"14pt\" "
        "style:font-size-complex=\"14pt\"/></style:style><style:style "
        "style:name=\"MP2\" "
        "style:family=\"paragraph\"><style:paragraph-properties "
        "fo:text-align=\"end\"/><style:text-properties fo:font-size=\"14pt\" "
        "style:font-size-asian=\"14pt\" "
        "style:font-size-complex=\"14pt\"/></style:style><style:style "
        "style:name=\"MP3\" "
        "style:family=\"paragraph\"><style:paragraph-properties "
        "fo:text-align=\"center\"/><style:text-properties "
        "fo:font-size=\"14pt\" style:font-size-asian=\"14pt\" "
        "style:font-size-complex=\"14pt\"/></style:style><style:style "
        "style:name=\"MT1\" style:family=\"text\"><style:text-properties "
        "fo:font-size=\"14pt\" style:font-size-asian=\"14pt\" "
        "style:font-size-complex=\"14pt\"/></style:style><text:list-style "
        "style:name=\"ML1\"><text:list-level-style-bullet text:level=\"1\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"2\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"0.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"3\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"4\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"5\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"2.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"6\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"7\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"8\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"9\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"10\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"5.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet></text:list-style"
        "><text:list-style style:name=\"ML2\"><text:list-level-style-bullet "
        "text:level=\"1\" "
        "text:bullet-char=\"●\"><style:list-level-properties/><style:text-pro"
        "perties fo:font-family=\"StarSymbol\" "
        "style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"2\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"0.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"3\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"4\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"1.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"5\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"2.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"6\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"7\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"3.6cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"8\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.2cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"9\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"4.8cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet><text:list-level-"
        "style-bullet text:level=\"10\" "
        "text:bullet-char=\"●\"><style:list-level-properties "
        "text:space-before=\"5.4cm\" "
        "text:min-label-width=\"0.6cm\"/><style:text-properties "
        "fo:font-family=\"StarSymbol\" style:use-window-font-color=\"true\" "
        "fo:font-size=\"45%\"/></text:list-level-style-bullet></text:list-style"
        "></office:automatic-styles><office:master-styles><draw:layer-set><draw"
        ":layer draw:name=\"layout\"/><draw:layer "
        "draw:name=\"background\"/><draw:layer "
        "draw:name=\"backgroundobjects\"/><draw:layer "
        "draw:name=\"controls\"/><draw:layer "
        "draw:name=\"measurelines\"/></draw:layer-set><style:handout-master "
        "presentation:presentation-page-layout-name=\"AL0T26\" "
        "style:page-layout-name=\"PM0\" "
        "draw:style-name=\"Mdp2\"><draw:page-thumbnail "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.294cm\" "
        "svg:height=\"6.97cm\" svg:x=\"1cm\" "
        "svg:y=\"2.435cm\"/><draw:page-thumbnail "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.294cm\" "
        "svg:height=\"6.97cm\" svg:x=\"1cm\" "
        "svg:y=\"10.483cm\"/><draw:page-thumbnail "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.294cm\" "
        "svg:height=\"6.97cm\" svg:x=\"1cm\" "
        "svg:y=\"18.531cm\"/><draw:page-thumbnail "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.294cm\" "
        "svg:height=\"6.97cm\" svg:x=\"11.295cm\" "
        "svg:y=\"2.435cm\"/><draw:page-thumbnail "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.294cm\" "
        "svg:height=\"6.97cm\" svg:x=\"11.295cm\" "
        "svg:y=\"10.483cm\"/><draw:page-thumbnail "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.294cm\" "
        "svg:height=\"6.97cm\" svg:x=\"11.295cm\" "
        "svg:y=\"18.531cm\"/><draw:frame draw:style-name=\"Mgr1\" "
        "draw:text-style-name=\"MP1\" draw:layer=\"backgroundobjects\" "
        "svg:width=\"9.369cm\" svg:height=\"1.396cm\" svg:x=\"0cm\" "
        "svg:y=\"0cm\" presentation:class=\"header\"><draw:text-box><text:p "
        "text:style-name=\"MP1\"><text:span "
        "text:style-name=\"MT1\"><presentation:header/></text:span></text:p></d"
        "raw:text-box></draw:frame><draw:frame draw:style-name=\"Mgr1\" "
        "draw:text-style-name=\"MP2\" draw:layer=\"backgroundobjects\" "
        "svg:width=\"9.369cm\" svg:height=\"1.396cm\" svg:x=\"12.22cm\" "
        "svg:y=\"0cm\" presentation:class=\"date-time\"><draw:text-box><text:p "
        "text:style-name=\"MP2\"><text:span "
        "text:style-name=\"MT1\"><presentation:date-time/></text:span></text:p>"
        "</draw:text-box></draw:frame><draw:frame draw:style-name=\"Mgr2\" "
        "draw:text-style-name=\"MP1\" draw:layer=\"backgroundobjects\" "
        "svg:width=\"9.369cm\" svg:height=\"1.396cm\" svg:x=\"0cm\" "
        "svg:y=\"26.543cm\" "
        "presentation:class=\"footer\"><draw:text-box><text:p "
        "text:style-name=\"MP1\"><text:span "
        "text:style-name=\"MT1\"><presentation:footer/></text:span></text:p></d"
        "raw:text-box></draw:frame><draw:frame draw:style-name=\"Mgr2\" "
        "draw:text-style-name=\"MP2\" draw:layer=\"backgroundobjects\" "
        "svg:width=\"9.369cm\" svg:height=\"1.396cm\" svg:x=\"12.22cm\" "
        "svg:y=\"26.543cm\" "
        "presentation:class=\"page-number\"><draw:text-box><text:p "
        "text:style-name=\"MP2\"><text:span "
        "text:style-name=\"MT1\"><text:page-number>&lt;number&gt;</text:page-nu"
        "mber></text:span></text:p></draw:text-box></draw:frame></style:handout"
        "-master><style:master-page style:name=\"Default\" "
        "style:page-layout-name=\"PM1\" draw:style-name=\"Mdp1\"><draw:frame "
        "presentation:style-name=\"Default-title\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"25.199cm\" "
        "svg:height=\"3.506cm\" svg:x=\"1.4cm\" svg:y=\"0.837cm\" "
        "presentation:class=\"title\" "
        "presentation:placeholder=\"true\"><draw:text-box/></draw:frame><draw:f"
        "rame presentation:style-name=\"Default-outline1\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"24.639cm\" "
        "svg:height=\"12.18cm\" svg:x=\"1.4cm\" svg:y=\"4.914cm\" "
        "presentation:class=\"outline\" "
        "presentation:placeholder=\"true\"><draw:text-box/></draw:frame><draw:f"
        "rame presentation:style-name=\"Mpr1\" draw:text-style-name=\"MP1\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"6.523cm\" "
        "svg:height=\"1.448cm\" svg:x=\"1.4cm\" svg:y=\"19.131cm\" "
        "presentation:class=\"date-time\"><draw:text-box><text:p "
        "text:style-name=\"MP1\"><text:span "
        "text:style-name=\"MT1\"><presentation:date-time/></text:span></text:p>"
        "</draw:text-box></draw:frame><draw:frame "
        "presentation:style-name=\"Mpr1\" draw:text-style-name=\"MP3\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"8.875cm\" "
        "svg:height=\"1.448cm\" svg:x=\"9.576cm\" svg:y=\"19.131cm\" "
        "presentation:class=\"footer\"><draw:text-box><text:p "
        "text:style-name=\"MP3\"><text:span "
        "text:style-name=\"MT1\"><presentation:footer/></text:span></text:p></d"
        "raw:text-box></draw:frame><draw:frame "
        "presentation:style-name=\"Mpr1\" draw:text-style-name=\"MP2\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"6.523cm\" "
        "svg:height=\"1.448cm\" svg:x=\"20.076cm\" svg:y=\"19.131cm\" "
        "presentation:class=\"page-number\"><draw:text-box><text:p "
        "text:style-name=\"MP2\"><text:span "
        "text:style-name=\"MT1\"><text:page-number>&lt;number&gt;</text:page-nu"
        "mber></text:span></text:p></draw:text-box></draw:frame><presentation:n"
        "otes style:page-layout-name=\"PM0\"><draw:page-thumbnail "
        "presentation:style-name=\"Default-title\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"13.968cm\" "
        "svg:height=\"10.476cm\" svg:x=\"3.81cm\" svg:y=\"2.123cm\" "
        "presentation:class=\"page\"/><draw:frame "
        "presentation:style-name=\"Default-notes\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"17.271cm\" "
        "svg:height=\"12.572cm\" svg:x=\"2.159cm\" svg:y=\"13.271cm\" "
        "presentation:class=\"notes\" "
        "presentation:placeholder=\"true\"><draw:text-box/></draw:frame><draw:f"
        "rame presentation:style-name=\"Mpr2\" draw:text-style-name=\"MP1\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.369cm\" "
        "svg:height=\"1.396cm\" svg:x=\"0cm\" svg:y=\"0cm\" "
        "presentation:class=\"header\"><draw:text-box><text:p "
        "text:style-name=\"MP1\"><text:span "
        "text:style-name=\"MT1\"><presentation:header/></text:span></text:p></d"
        "raw:text-box></draw:frame><draw:frame "
        "presentation:style-name=\"Mpr2\" draw:text-style-name=\"MP2\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.369cm\" "
        "svg:height=\"1.396cm\" svg:x=\"12.22cm\" svg:y=\"0cm\" "
        "presentation:class=\"date-time\"><draw:text-box><text:p "
        "text:style-name=\"MP2\"><text:span "
        "text:style-name=\"MT1\"><presentation:date-time/></text:span></text:p>"
        "</draw:text-box></draw:frame><draw:frame "
        "presentation:style-name=\"Mpr3\" draw:text-style-name=\"MP1\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.369cm\" "
        "svg:height=\"1.396cm\" svg:x=\"0cm\" svg:y=\"26.543cm\" "
        "presentation:class=\"footer\"><draw:text-box><text:p "
        "text:style-name=\"MP1\"><text:span "
        "text:style-name=\"MT1\"><presentation:footer/></text:span></text:p></d"
        "raw:text-box></draw:frame><draw:frame "
        "presentation:style-name=\"Mpr3\" draw:text-style-name=\"MP2\" "
        "draw:layer=\"backgroundobjects\" svg:width=\"9.369cm\" "
        "svg:height=\"1.396cm\" svg:x=\"12.22cm\" svg:y=\"26.543cm\" "
        "presentation:class=\"page-number\"><draw:text-box><text:p "
        "text:style-name=\"MP2\"><text:span "
        "text:style-name=\"MT1\"><text:page-number>&lt;number&gt;</text:page-nu"
        "mber></text:span></text:p></draw:text-box></draw:frame></presentation:"
        "notes></style:master-page></office:master-styles></office:document-sty"
        "les>\n"
};

const char* content = {
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    "<office:document-content "
    "xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" "
    "xmlns:style=\"urn:oasis:names:tc:opendocument:xmlns:style:1.0\" "
    "xmlns:text=\"urn:oasis:names:tc:opendocument:xmlns:text:1.0\" "
    "xmlns:table=\"urn:oasis:names:tc:opendocument:xmlns:table:1.0\" "
    "xmlns:draw=\"urn:oasis:names:tc:opendocument:xmlns:drawing:1.0\" "
    "xmlns:fo=\"urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
    "\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" "
    "xmlns:dc=\"http://purl.org/dc/elements/1.1/\" "
    "xmlns:meta=\"urn:oasis:names:tc:opendocument:xmlns:meta:1.0\" "
    "xmlns:number=\"urn:oasis:names:tc:opendocument:xmlns:datastyle:1.0\" "
    "xmlns:presentation=\"urn:oasis:names:tc:opendocument:xmlns:presentatio"
    "n:1.0\" "
    "xmlns:svg=\"urn:oasis:names:tc:opendocument:xmlns:svg-compatible:1.0\""
    " xmlns:chart=\"urn:oasis:names:tc:opendocument:xmlns:chart:1.0\" "
    "xmlns:dr3d=\"urn:oasis:names:tc:opendocument:xmlns:dr3d:1.0\" "
    "xmlns:math=\"http://www.w3.org/1998/Math/MathML\" "
    "xmlns:form=\"urn:oasis:names:tc:opendocument:xmlns:form:1.0\" "
    "xmlns:script=\"urn:oasis:names:tc:opendocument:xmlns:script:1.0\" "
    "xmlns:ooo=\"http://openoffice.org/2004/office\" "
    "xmlns:ooow=\"http://openoffice.org/2004/writer\" "
    "xmlns:oooc=\"http://openoffice.org/2004/calc\" "
    "xmlns:dom=\"http://www.w3.org/2001/xml-events\" "
    "xmlns:xforms=\"http://www.w3.org/2002/xforms\" "
    "xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" "
    "xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" "
    "xmlns:smil=\"urn:oasis:names:tc:opendocument:xmlns:smil-compatible:1.0"
    "\" xmlns:anim=\"urn:oasis:names:tc:opendocument:xmlns:animation:1.0\" "
    "xmlns:rpt=\"http://openoffice.org/2005/report\" "
    "xmlns:of=\"urn:oasis:names:tc:opendocument:xmlns:of:1.2\" "
    "xmlns:xhtml=\"http://www.w3.org/1999/xhtml\" "
    "xmlns:grddl=\"http://www.w3.org/2003/g/data-view#\" "
    "xmlns:officeooo=\"http://openoffice.org/2009/office\" "
    "xmlns:tableooo=\"http://openoffice.org/2009/table\" "
    "xmlns:drawooo=\"http://openoffice.org/2010/draw\" "
    "xmlns:field=\"urn:openoffice:names:experimental:ooo-ms-interop:xmlns:f"
    "ield:1.0\" "
    "xmlns:formx=\"urn:openoffice:names:experimental:ooxml-odf-interop:xmln"
    "s:form:1.0\" xmlns:css3t=\"http://www.w3.org/TR/css3-text/\" "
    "office:version=\"1.2\"><office:scripts/><office:automatic-styles><styl"
    "e:style style:name=\"dp1\" "
    "style:family=\"drawing-page\"><style:drawing-page-properties "
    "presentation:background-visible=\"true\" "
    "presentation:background-objects-visible=\"true\" "
    "presentation:display-footer=\"true\" "
    "presentation:display-page-number=\"false\" "
    "presentation:display-date-time=\"true\"/></style:style><style:style "
    "style:name=\"dp2\" "
    "style:family=\"drawing-page\"><style:drawing-page-properties "
    "presentation:display-header=\"true\" "
    "presentation:display-footer=\"true\" "
    "presentation:display-page-number=\"false\" "
    "presentation:display-date-time=\"true\"/></style:style><style:style "
    "style:name=\"gr1\" style:family=\"graphic\" "
    "style:parent-style-name=\"standard\"><style:graphic-properties "
    "draw:stroke=\"none\" draw:fill=\"none\" "
    "draw:textarea-horizontal-align=\"center\" "
    "draw:textarea-vertical-align=\"middle\" draw:color-mode=\"standard\" "
    "draw:luminance=\"0%\" draw:contrast=\"0%\" draw:gamma=\"100%\" "
    "draw:red=\"0%\" draw:green=\"0%\" draw:blue=\"0%\" "
    "fo:clip=\"rect(0cm, 0cm, 0cm, 0cm)\" draw:image-opacity=\"100%\" "
    "style:mirror=\"none\"/></style:style><style:style style:name=\"gr2\" "
    "style:family=\"graphic\"><style:graphic-properties "
    "style:protect=\"size\"/></style:style><style:style style:name=\"pr1\" "
    "style:family=\"presentation\" "
    "style:parent-style-name=\"Default-notes\"><style:graphic-properties "
    "draw:fill-color=\"#ffffff\" "
    "fo:min-height=\"12.572cm\"/></style:style><style:style "
    "style:name=\"P1\" "
    "style:family=\"paragraph\"><style:paragraph-properties "
    "fo:text-align=\"center\"/></style:style></office:automatic-styles><off"
    "ice:body><office:presentation>\n"
    "\n"
    "##PAGE_LIST##\n"
    "\n"
    "<presentation:settings "
    "presentation:mouse-visible=\"false\"/></office:presentation></office:b"
    "ody></office:document-content>\n"
};

const char* meta = {
        "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
        "<office:document-meta "
        "xmlns:office=\"urn:oasis:names:tc:opendocument:xmlns:office:1.0\" "
        "xmlns:xlink=\"http://www.w3.org/1999/xlink\" "
        "xmlns:dc=\"http://purl.org/dc/elements/1.1/\" "
        "xmlns:meta=\"urn:oasis:names:tc:opendocument:xmlns:meta:1.0\" "
        "xmlns:presentation=\"urn:oasis:names:tc:opendocument:xmlns:presentatio"
        "n:1.0\" xmlns:ooo=\"http://openoffice.org/2004/office\" "
        "xmlns:smil=\"urn:oasis:names:tc:opendocument:xmlns:smil-compatible:1.0"
        "\" xmlns:anim=\"urn:oasis:names:tc:opendocument:xmlns:animation:1.0\" "
        "xmlns:grddl=\"http://www.w3.org/2003/g/data-view#\" "
        "xmlns:officeooo=\"http://openoffice.org/2009/office\" "
        "xmlns:drawooo=\"http://openoffice.org/2010/draw\" "
        "office:version=\"1.2\"><office:meta><meta:initial-creator>##USERNAME##"
        "</meta:initial-creator><meta:creation-date>##DATE_TIME##</meta:cre"
        "ation-date><dc:date>##DATE_TIME##</dc:date><dc:creator>##USERNAME"
        "##</dc:creator><meta:editing-duration>P0D</meta:editing-duration><meta"
        ":editing-cycles>1</meta:editing-cycles><meta:generator>"
        "##GENERATOR_NAME##</meta:generator><meta:document-statistic "
        "meta:object-count=\"##OBJECT_COUNT##\"/></office:meta></office:documen"
        "t-meta>\n"
};

const char* manifest = {
    "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
    "<manifest:manifest "
    "xmlns:manifest=\"urn:oasis:names:tc:opendocument:xmlns:manifest:1.0\" "
    "manifest:version=\"1.2\">\n"
    " <manifest:file-entry "
    "manifest:media-type=\"application/vnd.oasis.opendocument.presentation\""
    " manifest:version=\"1.2\" manifest:full-path=\"/\"/>\n"
    " ##IMAGE_LIST##\n"
    " <manifest:file-entry manifest:media-type=\"text/xml\" "
    "manifest:full-path=\"meta.xml\"/>\n"
    " <manifest:file-entry manifest:media-type=\"text/xml\" "
    "manifest:full-path=\"settings.xml\"/>\n"
    " <manifest:file-entry manifest:media-type=\"text/xml\" "
    "manifest:full-path=\"content.xml\"/>\n"
    //" <manifest:file-entry manifest:media-type=\"\" "
    //"manifest:full-path=\"Configurations2/accelerator/current.xml\"/>\n"
    //" <manifest:file-entry "
    //"manifest:media-type=\"application/vnd.sun.xml.ui.configuration\" "
    //"manifest:full-path=\"Configurations2/\"/>\n"
    " <manifest:file-entry manifest:media-type=\"text/xml\" "
    "manifest:full-path=\"styles.xml\"/>\n"
    "</manifest:manifest>\n"
};

const char* pageEntry = {
    "<draw:page draw:name=\"page##PAGE_NUMBER##\" draw:style-name=\"dp1\" "
    "draw:master-page-name=\"Default\" "
    "presentation:presentation-page-layout-name=\"AL1T0\"><draw:frame "
    "draw:style-name=\"gr1\" draw:text-style-name=\"P1\" "
    "draw:layer=\"layout\" svg:width=\"27.998cm\" svg:height=\"20.999cm\" "
    "svg:x=\"0.000cm\" svg:y=\"0.000cm\"><draw:image "
    "xlink:href=\"Pictures/##IMAGE_NAME##\" xlink:type=\"simple\" "
    "xlink:show=\"embed\" "
    "xlink:actuate=\"onLoad\"><text:p/></draw:image></draw:frame><presentat"
    "ion:notes draw:style-name=\"dp2\"><draw:page-thumbnail "
    "draw:style-name=\"gr2\" draw:layer=\"layout\" svg:width=\"13.968cm\" "
    "svg:height=\"10.476cm\" svg:x=\"3.81cm\" svg:y=\"2.123cm\" "
    "draw:page-number=\"##PAGE_NUMBER##\" "
    "presentation:class=\"page\"/><draw:frame "
    "presentation:style-name=\"pr1\" draw:layer=\"layout\" "
    "svg:width=\"17.271cm\" svg:height=\"12.572cm\" svg:x=\"2.159cm\" "
    "svg:y=\"13.271cm\" presentation:class=\"notes\" "
    "presentation:placeholder=\"true\"><draw:text-box/></draw:frame></prese"
    "ntation:notes></draw:page>\n"
};

const char* manifestEntry = {
    "<manifest:file-entry manifest:media-type=\"##IMAGE_TYPE##\" manifest"
    ":full-path=\"Pictures/##IMAGE_NAME##\"/>"
};

} //namespace
